#!/bin/sh

# Use neovim for vim if present.
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d"

# Verbosity and settings that you pretty much just always are going to want.
alias \
	bat="cat /sys/class/power_supply/BAT?/capacity" \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -v" \
	mkd="mkdir -pv" \
	yt="youtube-dl --add-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner" \
        xbl="xbacklight -time 0 -set" \
        man="man --ascii" \
        tt="nohup sxiv -Z /home/andrew/Downloads/Pictures/wallpapers1.png > /dev/null &" \
        perf="sudo cpupower frequency-set -r -u 3.9GHz" \
        save="sudo cpupower frequency-set -r -u 1.6GHz"

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	trem="transmission-remote" \
	YT="youtube-viewer" \
	sdn="sudo shutdown -h now" \
	f="$FILE" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="sudo pacman" \
	xi="sudo xbps-install" \
	xr="sudo xbps-remove -R" \
	xq="xbps-query"

# This alias is important. It enables the `pauseallmpv` command.
alias mpv="mpv --input-ipc-server=/tmp/mpvsoc$(date +%s)"
alias sshfs_switcher="sudo sshfs pi@switcher:/home/pi /home/andrew/Mount/switcher"
alias sshfs_serv="sudo sshfs root@matrix-mipt.xyz:/ /home/andrew/Mount/serv"

# Some other stuff
alias \
	ref="shortcuts >/dev/null; source ~/.config/shortcutrc" \
