version: 2.1

executors:
  golangci-lint:
    docker:
      - image: golangci/golangci-lint:v1.25.0
  go:
    docker:
      - image: vansante/go-ffprobe:latest

jobs:
  lint:
    executor: golangci-lint
    steps:
      - checkout
      - run: golangci-lint run

  test:
    executor: go
    steps:
      - checkout
      - run: go get github.com/jstemmer/go-junit-report
      - run: mkdir -p /tmp/test-results
      - run: go test -v -race ./... | go-junit-report > /tmp/test-results/spec.xml
      - store_test_results:
          path: /tmp/test-results

workflows:
  version: 2
  main:
    jobs:
      - lint
      - test